### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Jun-Kataoka** [Jun-Kataoka/furima-36078#9]
# フリマアプリのURL
https://furima-36078.herokuapp.com/

# Basic認証のID
admin
# Basic認証のパスワード
2222

# 出品者用のメールアドレス
seller@mail
# 出品者用のパスワード
aaa111

# 購入者用のメールアドレス
buyer@mail
# 購入者用のパスワード
aaa111

**Comment by takumi0530** [comment]
@Jun-Kataoka さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **クレジットカード決済ができること**
「Token can't be blank」と出てしまい、決済できませんでした。
**※上記により、購入機能・売却後の動作確認ができておりません。次回ご提出時に確認させていただきます。**

**【入力したPAY.JPのテストカード情報】**
```
・カード番号が4242424242424242
・CVCが3桁または4桁の半角数字
・有効期限の日付が登録時より未来
```

- [x] **本番環境で投稿した商品画像が、S3に保存されること**
現在active_storageにて保存されております。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takumi0530** [comment]
@Jun-Kataoka さん、再度ご提出ありがとうございます‼︎
動作の確認をしたところ、改めて修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **本番環境で投稿した商品画像が、S3に保存されること**
現在active_storageにて保存されております。プッシュやデプロイ忘れなどないかご確認をお願いいたします。

- [x] **ログイン状態の出品者であっても、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること**
出品者で自身の出品した売却済の商品の編集ページに遷移しようとすると、遷移できてしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takumi0530** [comment]
@Jun-Kataoka さん、お待たせいたしました。 再度ご提出ありがとうございます‼︎
動作の確認をしたところ、修正が確認できませんでした。
**マージやデプロイ忘れの可能性**もありますので、改めてご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **ログイン状態の出品者であっても、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること**
出品者で自身の出品した売却済の商品の編集ページに遷移しようとすると、遷移できてしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Jun-Kataoka** [comment]
こちらでも確認したところ問題なく動いている様に見えます。
[確認動画](https://gyazo.com/a75c886101b0394e51f90a4f8918faa5)

**Comment by takumi0530** [comment]
@Jun-Kataoka さん、ご質問ありがとうございます！

- [x] **ログイン状態の出品者であっても、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること**
出品者で自身の出品した売却済の商品の編集ページに遷移しようとすると、遷移できてしまいます。

今回の場合ですと、売却済に商品を出品したユーザーでログインした場合に起こるものとなっております。
実際の動作を収録いたしましたので、ご確認いただけると幸いです。

**◾︎「lifecoach_test_user1」でログインし、自身で出品した商品（売却済）の編集ページに遷移してしまう際の画面収録**
https://user-images.githubusercontent.com/76197191/126947381-7276148d-0cf3-45c4-a339-685b4bfa360c.mov


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Jun-Kataoka** [comment]
購入ページと勘違いしておりました。
失礼いたしました。

**Comment by takumi0530** [comment]
@Jun-Kataoka さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/126952991-e4d87730-35f9-4d45-b16e-b3a8f4ddbc3d.png)
